### ISSUE TITLE
Documentation: Module Functionality

### ISSUE THREAD

**Issue by ShinyMiraidon** [NYU-Processor-Design/nyu-core#30]
Need to convert the complete module descriptions in the issues into proper documentation files that can go in their own folder and be updated as the module is implemented and iterated on

**Comment by gil92723** [comment]
So do you mean like make all the files first with disclaimer?

And as for the template I'll get on that rn

**Comment by umanachi** [comment]
do you want a copy of each doc in the wiki or just links to the md files within the repo
